import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { portfolioData } from '../src/devData.js'

export const root = fileURLToPath(new URL('../', import.meta.url))
export const contentHash = createHash('sha256').update(JSON.stringify(portfolioData)).digest('hex')

const escapeHtml = (text) => text.replace(/[&<>"']/g, (character) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
})[character])

export function documents(data = portfolioData) {
  const { site, personalInfo: person, education, experience, projects, skills } = data
  const url = (path = '/') => new URL(path, `${site.origin}/`).href
  const profile = {
    '@type': 'Person', '@id': url('/#person'), name: person.name,
    url: url(), jobTitle: person.role, description: person.summary,
    email: `mailto:${person.email}`, sameAs: [person.github, person.linkedin],
    alumniOf: { '@type': 'CollegeOrUniversity', name: education.institution },
    hasCredential: { '@type': 'EducationalOccupationalCredential', name: education.degree, credentialCategory: 'degree' },
    knowsAbout: Object.values(skills).flat(),
  }
  const projectList = {
    '@type': 'ItemList', '@id': url('/#project-list'), name: `Projects by ${person.name}`,
    itemListElement: projects.map((project, index) => ({
      '@type': 'ListItem', position: index + 1,
      item: {
        '@type': project.githubLink ? 'SoftwareSourceCode' : 'CreativeWork',
        '@id': url(`/#${project.id}`), url: url(`/#${project.id}`),
        name: project.title, description: `${project.summary} ${project.impact}`,
        ...(project.githubLink ? { codeRepository: project.githubLink } : {}),
      },
    })),
  }

  function html(path, title, description) {
    const schema = JSON.stringify({
      '@context': 'https://schema.org',
      '@graph': [
        { '@type': 'ProfilePage', '@id': url(path), url: url(path), name: title,
          dateModified: site.updated, mainEntity: { '@id': url('/#person') },
          isPartOf: { '@id': url('/#website') } },
        profile,
        { '@type': 'WebSite', '@id': url('/#website'), name: `${person.name} Portfolio`,
          url: url(), inLanguage: 'en', publisher: { '@id': url('/#person') } },
        projectList,
      ],
    }, null, 2).replace(/</g, '\\u003c')

    return `<!doctype html>
<!-- Generated by bun run content:generate. Edit src/devData.js or scripts/content.mjs. -->
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <meta name="description" content="${escapeHtml(description)}" />
  <meta name="author" content="${escapeHtml(person.name)}" />
  <meta name="robots" content="index, follow, max-image-preview:large" />
  <link rel="canonical" href="${url(path)}" />
  <link rel="sitemap" type="application/xml" href="/sitemap.xml" />
  <link rel="alternate" type="text/plain" href="/llms.txt" title="Portfolio summary" />
  <link rel="alternate" type="text/plain" href="/llms-full.txt" title="Full portfolio context" />
  <link rel="preload" href="/fonts/playfair-display-latin.woff2" as="font" type="font/woff2" crossorigin />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="${url(path)}" />
  <meta property="og:title" content="${escapeHtml(title)}" />
  <meta property="og:description" content="${escapeHtml(description)}" />
  <meta property="og:image" content="${url(site.socialImage)}" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:type" content="image/png" />
  <meta property="og:image:alt" content="${escapeHtml(person.name)} - ${escapeHtml(person.role)}" />
  <meta property="og:site_name" content="${escapeHtml(person.name)} Portfolio" />
  <meta property="og:locale" content="en_US" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${escapeHtml(title)}" />
  <meta name="twitter:description" content="${escapeHtml(description)}" />
  <meta name="twitter:image" content="${url(site.socialImage)}" />
  <meta name="twitter:image:alt" content="${escapeHtml(person.name)} - ${escapeHtml(person.role)}" />
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <link rel="apple-touch-icon" href="/icon512_rounded.png" />
  <link rel="manifest" href="/manifest.json" />
  <meta name="theme-color" content="#ffffff" />
  <meta name="color-scheme" content="light" />
  <meta name="google-site-verification" content="WVVgNbMhmec_t3jLFhdOeuEsQF1b6mCfrE8_h9PpO-8" />
  <script type="application/ld+json">${schema}</script>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.jsx"></script>
</body>
</html>
`
  }

  const skillsText = Object.entries(skills).map(([key, values]) => {
    const labels = { languages: 'Languages', frameworks: 'Frameworks', data: 'Data and databases', aiMl: 'AI and ML', cloudTools: 'Cloud and DevOps', securityTools: 'Security and tools' }
    return `- **${labels[key]}:** ${values.join(', ')}`
  }).join('\n')
  const links = `- [Portfolio](${url()})\n- [PDF resume](${url(person.resumePath)})\n- [GitHub](${person.github})\n- [LinkedIn](${person.linkedin})\n- [Email ${person.name}](mailto:${person.email})`
  const intro = `# ${person.name} - ${person.role}\n\n> ${person.summary}\n\nLast updated: ${site.updated}. Biography and private-project descriptions are owner-provided. Public repository links document implementation details, not independently audited outcomes.\n`
  const projectText = projects.map((project) => `### ${project.title}\n\n${project.summary}\n\n${project.impact}\n\n- Focus: ${project.focus}\n- Stack: ${project.technologies.join(', ')}\n- [Portfolio entry](${url(`/#${project.id}`)})${project.deploymentLink ? `\n- [Live site](${project.deploymentLink})` : ''}${project.githubLink ? `\n- [Source code](${project.githubLink})` : '\n- Source not published'}${project.infoLink ? `\n- [Technical documentation, inspected revision](${project.infoLink})` : ''}`).join('\n\n')
  const experienceText = experience.map((job) => `### ${job.role}, ${job.company}\n\n${job.date}\n\n${job.responsibilities.map((text) => `- ${text}`).join('\n')}`).join('\n\n')
  const educationText = `${education.institution}\n\n${education.degree}\n\n${education.honors}\n\n${education.extraCurriculars}\n\n${education.achievements.map((text) => `- ${text}`).join('\n')}\n\nCoursework: ${education.relevantCoursework.join(', ')}`

  return new Map([
    ['index.html', html('/', site.title, site.description)],
    ['public/llms.txt', `${intro}\n## Contact and links\n\n${links}\n- [Full portfolio context](${url('/llms-full.txt')})\n\n## Experience\n\n${experience.map((job) => `- **${job.role}, ${job.company}** (${job.date}): ${job.responsibilities[0]}`).join('\n')}\n\n## Projects\n\n${projects.map((project) => `- [${project.title}](${url(`/#${project.id}`)}): ${project.summary}`).join('\n')}\n\n## Skills\n\n${skillsText}\n\n## Education\n\n${educationText}\n`],
    ['public/llms-full.txt', `${intro}\n## Contact and links\n\n${links}\n\n## Experience\n\n${experienceText}\n\n## Projects\n\n${projectText}\n\n## Skills\n\n${skillsText}\n\n## Education\n\n${educationText}\n`],
    ['public/ai.txt', `# ${person.name} Portfolio\n\n${person.summary}\n\nLast updated: ${site.updated}.\n\n- [Canonical portfolio](${url()})\n- [Portfolio summary](${url('/llms.txt')})\n- [Full portfolio context and source links](${url('/llms-full.txt')})\n- [PDF resume](${url(person.resumePath)})\n\nThese documents are generated from the same content as the website. Public repository descriptions are not independently verified performance or clinical claims.\n`],
    ['public/robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${url('/sitemap.xml')}\n`],
    ['public/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url>\n    <loc>${url('/')}</loc>\n    <lastmod>${site.updated}</lastmod>\n  </url>\n</urlset>\n`],
    ['public/manifest.json', `${JSON.stringify({
      name: `${person.name} - ${person.role}`, short_name: person.name,
      description: site.description, start_url: '/', scope: '/', id: '/', display: 'browser',
      lang: 'en', theme_color: '#ffffff', background_color: '#ffffff',
      icons: [
        { src: '/icon512_maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        { src: '/icon512_rounded.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      ],
    }, null, 2)}\n`],
  ])
}

export async function generateContent(check = false) {
  const stale = []
  for (const [path, content] of documents()) {
    const file = resolve(root, path)
    const current = await readFile(file, 'utf8').catch((error) => {
      if (error.code !== 'ENOENT') throw error
      return null
    })
    if (current === content) continue
    if (check) stale.push(path)
    else {
      await mkdir(dirname(file), { recursive: true })
      await writeFile(file, content)
    }
  }
  if (stale.length) throw new Error(`Generated content is stale: ${stale.join(', ')}. Run bun run content:generate.`)
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await generateContent(process.argv.includes('--check'))
  console.log(process.argv.includes('--check') ? 'Generated content is current.' : 'Generated content is synchronized.')
}
